version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node-app
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - '8080:8080'